import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, ChevronUp, BookOpen, AlertTriangle, HelpCircle } from 'lucide-react';
import { VisualizerStage } from '../engine/queryRewriter';
import { useQueryStore } from '../store/useQueryStore';
import TableRenderer from './TableRenderer';

interface StageCardProps {
  stage: VisualizerStage;
  stageNumber: number;
}

// Plain English explanations and educational copy for each stage
const EDUCATIONAL_CONTENT: Record<string, {
  summary: string;
  details: string;
  pitfall: string;
  cost: 'Low' | 'Medium' | 'High';
}> = {
  from: {
    summary: "Loads the initial tables and performs JOIN operations to merge matching rows.",
    details: "This is the very first step. The database identifies which tables are referenced. If multiple tables are joined, it evaluates the join criteria. For a CROSS JOIN, it performs a Cartesian Product, combining every row of table A with every row of table B, which can grow extremely fast.",
    pitfall: "Joining without columns that are indexed, or running CROSS JOINS on large tables will produce immense temporary results and cause severe slow-downs.",
    cost: "High"
  },
  where: {
    summary: "Filters out rows that do not match the WHERE conditions.",
    details: "The database scans the rows generated by the FROM/JOIN stage and evaluates the WHERE predicate (e.g., age > 25) for each row. Only rows that evaluate to TRUE are passed to the next stage.",
    pitfall: "You cannot use aggregate functions (like SUM or AVG) in a WHERE clause because grouping has not happened yet! Use HAVING for aggregates.",
    cost: "Medium"
  },
  groupby: {
    summary: "Groups the matching rows into buckets based on matching column values.",
    details: "Rows are partitioned into distinct buckets where the values of the GROUP BY columns are identical. All subsequent operations (aggregates like COUNT or SUM) will evaluate per bucket rather than per individual row.",
    pitfall: "Once grouped, you can generally only SELECT columns that are either part of the GROUP BY keys, or are wrapped inside aggregate functions. Selecting anything else will throw an error in most databases.",
    cost: "Medium"
  },
  having: {
    summary: "Filters the groups generated by GROUP BY, removing non-matching buckets.",
    details: "Just like WHERE filters rows, HAVING filters groups. It runs after GROUP BY and evaluates aggregate expressions (e.g., AVG(salary) > 60000) for each group bucket. Only buckets evaluating to TRUE survive.",
    pitfall: "Don't confuse WHERE and HAVING. Use WHERE to filter rows before grouping (which is much faster), and use HAVING only when you need to filter based on aggregated results.",
    cost: "Low"
  },
  select: {
    summary: "Projects the specified columns and calculates aggregates for each group.",
    details: "The database selects the specific columns you requested. If grouping was applied, it evaluates aggregate functions (like SUM, COUNT, AVG) over the rows inside each group, collapsing each bucket into a single final row.",
    pitfall: "Avoid using SELECT * in production. It forces the database to fetch unnecessary columns, wasting CPU and memory. Always project only the columns you need.",
    cost: "Low"
  },
  distinct: {
    summary: "Eliminates duplicate rows from the final result set.",
    details: "The database scans the projected results and removes identical rows so that each combination of values is unique. This is performed by sorting or using a temporary hash table.",
    pitfall: "DISTINCT adds computational overhead because the database must check every row against every other row to find duplicates. Use it only when duplicates are actually possible and undesirable.",
    cost: "Medium"
  },
  orderby: {
    summary: "Sorts the final rows in ascending or descending order.",
    details: "The database reorders the rows according to the columns specified in the ORDER BY clause. If multiple columns are provided, it sorts by the first, using the second to resolve ties.",
    pitfall: "Sorting is a CPU-intensive operation. If the sorted column is not indexed, the database must perform an in-memory sort (filesort), which can be very slow for large datasets.",
    cost: "Medium"
  },
  limit: {
    summary: "Slices the rows, returning only the requested range.",
    details: "This is the final stage. The database takes the sorted result set, skips the number of rows specified in OFFSET, and returns the maximum number of rows specified in LIMIT.",
    pitfall: "Running a LIMIT without an ORDER BY clause yields unpredictable results. The database does not guarantee a default row order, so the rows returned could change between executions.",
    cost: "Low"
  },
  ddl: {
    summary: "Defines or alters database schemas (tables, constraints, indexes).",
    details: "Data Definition Language (DDL) creates the physical structure in the database. CREATE TABLE sets up the columns, data types, and primary key constraints.",
    pitfall: "Modifying table schemas on active databases can lock tables and block read/write operations for other users.",
    cost: "Low"
  },
  dml: {
    summary: "Modifies database records (INSERT, UPDATE, DELETE).",
    details: "Data Manipulation Language (DML) writes or deletes rows. INSERT slides new records into a table, UPDATE mutates existing cells, and DELETE wipes matching rows.",
    pitfall: "Always test UPDATE and DELETE statements with a WHERE clause first. Omitting the WHERE clause will update or delete every single row in the table!",
    cost: "Medium"
  }
};

export default function StageCard({ stage, stageNumber }: StageCardProps) {
  const [isOpen, setIsOpen] = useState(true);
  const [showEdu, setShowEdu] = useState(false);
  const setActiveStageId = useQueryStore((state) => state.setActiveStageId);
  const activeStageId = useQueryStore((state) => state.activeStageId);

  const edu = EDUCATIONAL_CONTENT[stage.id] || {
    summary: "Executes database logical processing.",
    details: "Processes columns and rows in sequence.",
    pitfall: "Ensure syntax and types match requirements.",
    cost: "Low" as const
  };

  const isHighlighted = activeStageId === stage.id;

  // Calculate change summary statistics
  const getStats = () => {
    if (!stage.rowStates) return null;
    const states = Object.values(stage.rowStates);
    const added = states.filter(s => s === 'added').length;
    const removed = states.filter(s => s === 'removed').length;
    const modified = states.filter(s => s === 'modified').length;

    const parts: string[] = [];
    if (added > 0) parts.push(`${added} added`);
    if (removed > 0) parts.push(`${removed} filtered/removed`);
    if (modified > 0) parts.push(`${modified} modified`);

    if (parts.length === 0) return `${stage.rows.length} rows active`;
    return parts.join(', ');
  };

  // Specialized GROUP BY renderer: partition rows into buckets
  const renderGroupByBuckets = () => {
    const groupedRows: Record<string, any[]> = {};
    stage.rows.forEach((row) => {
      const key = row.__group_key || 'Unassigned';
      if (!groupedRows[key]) groupedRows[key] = [];
      groupedRows[key].push(row);
    });

    return (
      <div className="space-y-4 my-2">
        {Object.entries(groupedRows).map(([groupVal, rowsInGroup]) => (
          <div 
            key={groupVal} 
            className="p-3 bg-brand-panel/20 border border-brand-border/60 rounded-lg hover:border-brand-cyan/20 transition-colors"
          >
            <div className="flex items-center justify-between mb-2">
              <span className="text-[11px] font-semibold text-slate-300">
                Group: <span className="text-brand-cyan font-mono">{groupVal}</span>
              </span>
              <span className="text-[10px] text-slate-500 font-mono">
                {rowsInGroup.length} row(s)
              </span>
            </div>
            <TableRenderer 
              columns={stage.columns} 
              rows={rowsInGroup} 
              rowStates={stage.rowStates}
            />
          </div>
        ))}
      </div>
    );
  };

  return (
    <div
      onMouseEnter={() => setActiveStageId(stage.id)}
      onMouseLeave={() => setActiveStageId(null)}
      className={`glass-panel border rounded-xl overflow-hidden transition-all duration-200 ${
        isHighlighted 
          ? 'border-brand-cyan shadow-[0_0_15px_rgba(0,212,255,0.08)] bg-brand-panel/70' 
          : 'border-brand-border bg-brand-panel/40'
      }`}
    >
      {/* Card Title Header */}
      <div 
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between px-4 py-3 cursor-pointer hover:bg-slate-800/10 select-none"
      >
        <div className="flex items-center space-x-3">
          <div className="flex items-center justify-center w-6 h-6 text-[10px] font-extrabold rounded-full bg-slate-900 border border-brand-border text-brand-cyan">
            {stageNumber}
          </div>
          <div>
            <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider">{stage.name}</h3>
            <p className="text-[11px] text-brand-text-muted font-sans mt-0.5">{edu.summary}</p>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          {/* Cost badge */}
          <span className={`text-[10px] px-1.5 py-0.5 rounded font-semibold ${
            edu.cost === 'High' ? 'bg-rose-950/40 text-rose-400 border border-rose-900/30' :
            edu.cost === 'Medium' ? 'bg-amber-950/40 text-amber-400 border border-amber-900/30' :
            'bg-emerald-950/40 text-emerald-400 border border-emerald-900/30'
          }`}>
            Cost: {edu.cost}
          </span>
          <span className="text-[10px] text-slate-500 font-mono bg-brand-bg/50 px-2 py-0.5 rounded border border-brand-border/40">
            {getStats()}
          </span>
          {isOpen ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
        </div>
      </div>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0 }}
            animate={{ height: 'auto' }}
            exit={{ height: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            {/* Card Body */}
            <div className="px-4 pb-4 pt-1 border-t border-brand-border/30 space-y-3">
              {/* Highlighted SQL Clause */}
              <div className="flex items-center justify-between px-3 py-1.5 bg-brand-bg/60 border border-brand-border/60 rounded-md font-mono text-xs">
                <code className="text-brand-cyan">{stage.sqlClause}</code>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowEdu(!showEdu);
                  }}
                  className="flex items-center space-x-1 text-[10px] font-semibold text-slate-400 hover:text-brand-cyan transition-colors"
                >
                  <BookOpen className="w-3.5 h-3.5" />
                  <span>{showEdu ? 'Hide Guide' : 'Explain Stage'}</span>
                </button>
              </div>

              {/* Collapsible Educational Guide */}
              <AnimatePresence>
                {showEdu && (
                  <motion.div
                    initial={{ opacity: 0, y: -5 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -5 }}
                    className="p-3 bg-brand-cyan-glow/5 border border-brand-cyan/20 rounded-lg text-xs leading-relaxed font-sans space-y-2 text-slate-300"
                  >
                    <div>
                      <span className="font-bold text-brand-cyan">What it does: </span>
                      {edu.details}
                    </div>
                    <div className="flex items-start space-x-1.5 p-2 bg-rose-950/10 border border-rose-900/20 rounded text-[11px] text-rose-300">
                      <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5 text-rose-400" />
                      <div>
                        <span className="font-bold">Common Pitfall: </span>
                        {edu.pitfall}
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Stage Table Renderer */}
              <div className="mt-2">
                {stage.id === 'groupby' ? (
                  renderGroupByBuckets()
                ) : (
                  <TableRenderer
                    columns={stage.columns}
                    rows={stage.rows}
                    rowStates={stage.rowStates}
                    highlightedColumns={stage.id === 'select' ? stage.columns : []}
                  />
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
